spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/entity
    username: postgres
    password: sa
    poolSize: 10
  hibernate:
    ddl: none
    format_Sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show_Sql: true
